version: "3"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    hostname: client
    restart: unless-stopped
    depends_on:
      - otelcol
      - server
    environment:
      - FIB_HOSTNAME=server
      - FIB_PORT=8080
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317
      - OTEL_SERVICE_NAME=client-service
      - OTEL_PROPAGATORS=tracecontext,baggage
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    hostname: server
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - otelcol
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.name=my-app-server
      - OTEL_PROPAGATORS=tracecontext,baggage
    expose:
      - 8080
  otelcol:
    image: otel/opentelemetry-collector-contrib:0.52.0
    container_name: otelcol
    hostname: otelcol
    command: ["--config=/config.yaml"]
    volumes:
        - ./config.yaml:/config.yaml
    depends_on:
      - zipkin
    ports:
      - 4317:4317
      - 4318:4318
      - 8888:8888
    expose:
      - 4317
      - 4318
      - 8888
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    hostname: zipkin
    ports:
      - 9411:9411
    expose:
      - 9411
