exporters:
  logging:
    loglevel: debug
  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans

receivers:
  otlp:
    protocols:
      grpc:
      http:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, zipkin]
