version: "3"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    hostname: client
    restart: unless-stopped
    depends_on:
      - server
    environment:
      - FIB_HOSTNAME=server
      - FIB_PORT=8080
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    hostname: server
    ports:
      - "8080:8080"
    restart: unless-stopped
    expose:
      - 8080
