FROM python:3.9-alpine

RUN apk update && apk upgrade && \
    apk add --no-cache bash

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . .

CMD ["python", "client.py"]